global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    app: atm-banking

scrape_configs:
  - job_name: 'banking-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 15s
    scrape_timeout: 10s
